name: pydelmod
channels:
  - pyviz
  - defaults
  - cadwr-dms
  - conda-forge
dependencies:
  - python=3.9
  - pip
  # first our packages
  - pyhecdss
  - vtools3
  - pydsm
  - pydelmod
  - schimpy
  # then basics
  - click
  - aiohttp
  - numba
  - pandas
  - dask
  - xarray
  - netcdf4
  - scipy
  # geo stuff
  - gdal
  - shapely
  - geopandas
  # for different file formats
  - fastparquet
  - python-snappy
  - pyarrow
  - pytables
  - openpyxl
  # then plot stuff
  - matplotlib
  - geoviews
  - holoviews
  - hvplot
  - networkx
  # browsers
  - autopep8
  # browsers
  - selenium
  - firefox
  - geckodriver
  # pdf parsing
  - tabula-py